#2026-09-22 17:47:49,007+0000
#Tue Sep 22 17:47:49 GMT 2026
@BlobStore.blob-name=health-check/maven-central/summary/protovis-tooltip.js
@BlobStore.created-by=repository-health-check
@BlobStore.direct-path=true
creationTime=1790099269002
sha1=770c3d5a7f360adabe7bac9cff0aa5c9fc41a8c0
size=2335
